name: Luxury Morning Brief

on:
  schedule:
    - cron: '0 21 * * *'  # 毎朝6時JST
  workflow_dispatch:

jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node research.mjs
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: research-results
          path: research.md

  write:
    needs: research
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - uses: actions/download-artifact@v4
        with:
          name: research-results
      - run: node ai-writer.mjs
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: article-draft
          path: |
            draft.json
            generated_article.md

  post:
    needs: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npx playwright install chromium
      - uses: actions/download-artifact@v4
        with:
          name: article-draft
      - run: node post.mjs
        env:
          NOTE_EMAIL: ${{ secrets.NOTE_EMAIL }}
          NOTE_PASSWORD: ${{ secrets.NOTE_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: post-results
          path: post_result.json
        if: always()

