name: AI Note Auto Posting

on:
  workflow_dispatch:
    inputs:
      theme:
        description: '記事のテーマ'
        required: true
        default: 'AI活用術'
      target:
        description: '想定読者'
        required: true
        default: 'ビジネスパーソン'
      message:
        description: '伝えたい核メッセージ'
        required: true
        default: 'AIで生産性向上'
      cta:
        description: '読後のアクション'
        required: false
        default: '実際に試してみる'
      is_public:
        description: '公開する（true/false）'
        required: true
        default: 'false'

jobs:
  ai-generate-and-post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install playwright @anthropic-ai/sdk
        npx playwright install chromium
        
    - name: Generate AI Article
      id: generate
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        ARTICLE=$(node ai-writer.mjs "${{ github.event.inputs.theme }}" "${{ github.event.inputs.target }}" "${{ github.event.inputs.message }}" "${{ github.event.inputs.cta }}")
        echo "article=$ARTICLE" >> $GITHUB_OUTPUT
        
    - name: Post to note
      env:
        NOTE_STORAGE_STATE_JSON: ${{ secrets.NOTE_STORAGE_STATE_JSON }}
      run: |
        echo '${{ env.NOTE_STORAGE_STATE_JSON }}' > note-state.json
        TITLE=$(echo '${{ steps.generate.outputs.article }}' | jq -r '.title')
        CONTENT=$(echo '${{ steps.generate.outputs.article }}' | jq -r '.content')
        TAGS=$(echo '${{ steps.generate.outputs.article }}' | jq -r '.tags | join(",")')
        node post.mjs "$TITLE" "$CONTENT" "$TAGS" "${{ github.event.inputs.is_public }}"
