name: Auto Post to Note

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前9時(JST)に実行
  workflow_dispatch:      # 手動実行も可能
    inputs:
      topic:
        description: '記事のトピック（空欄可）'
        required: false
        default: ''
      target_audience:
        description: 'ターゲット読者'
        required: false
        default: 'ラグジュアリーブランドやMBB、コンサル業界のプロフェッショナル'
      thinking_memo:
        description: '思考メモ（書きたい内容、気になっていること、断片的なアイデアなど自由にコピペ）'
        required: false
        default: ''
      direction:
        description: '記事の方向性（分析系/事例紹介/トレンド解説/実務Tips など、空欄可）'
        required: false
        default: ''
      focus_area:
        description: '特に深掘りしたい領域（ブランド名、地域、テーマなど、空欄可）'
        required: false
        default: ''

jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run research
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          TOPIC: ${{ github.event.inputs.topic || '' }}
          TARGET_AUDIENCE: ${{ github.event.inputs.target_audience || 'ラグジュアリーブランドやMBB、コンサル業界のプロフェッショナル' }}
          THINKING_MEMO: ${{ github.event.inputs.thinking_memo || '' }}
          DIRECTION: ${{ github.event.inputs.direction || '' }}
          FOCUS_AREA: ${{ github.event.inputs.focus_area || '' }}
        run: node research.mjs

      - name: Upload research results
        uses: actions/upload-artifact@v3
        with:
          name: research-results
          path: research.md

  write:
    needs: research
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Download research results
        uses: actions/download-artifact@v3
        with:
          name: research-results

      - name: Generate article
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          TOPIC: ${{ github.event.inputs.topic || '' }}
          TARGET_AUDIENCE: ${{ github.event.inputs.target_audience || 'ラグジュアリーブランドやMBB、コンサル業界のプロフェッショナル' }}
          THINKING_MEMO: ${{ github.event.inputs.thinking_memo || '' }}
          DIRECTION: ${{ github.event.inputs.direction || '' }}
          FOCUS_AREA: ${{ github.event.inputs.focus_area || '' }}
        run: node ai-writer.mjs

      - name: Upload draft
        uses: actions/upload-artifact@v3
        with:
          name: article-draft
          path: |
            draft.json
            generated_article.md

  post:
    needs: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Download draft
        uses: actions/download-artifact@v3
        with:
          name: article-draft

      - name: Post to Note
        env:
          NOTE_EMAIL: ${{ secrets.NOTE_EMAIL }}
          NOTE_PASSWORD: ${{ secrets.NOTE_PASSWORD }}
        run: node post.mjs

      - name: Upload post results
        uses: actions/upload-artifact@v3
        with:
          name: post-results
          path: post_result.json
        if: always()
